### ISSUE TITLE
Missing DHT Type

### ISSUE THREAD

**Issue by the-programmer** [pimatic/homeduinojs#5]
Hi,

While trying to add a AM2301 I stumbled on a problem. According to the DHTLib http://playground.arduino.cc//Main/DHTLib my sensor is a DHT21 so I added this as type. However that generates errors.
On line 204 of "board.js" you require the types to be any of the following:
11,22,33,44 or 55. However the 21 is missing from this list.

Could you add this as well?

**Comment by the-programmer** [comment]
Note: I just updated my config file so that it uses the 22 type and now the system runs file.
All that has to be done is change line 204 to:

```
assert(type === 11 || type === 21 || type === 22 || type === 33 || type === 44 || type === 55);
```

**Comment by sweetpi** [comment]
Thanks for pointing this out, fixed.
