### ISSUE TITLE
timed out

### ISSUE THREAD

**Issue by ivo1981** [pimatic/homeduinojs#6]
after npm install I tired to run the client; however I received a timed out error:
pi@raspberrypi:~/homeduinojs$ sudo ./client.js /dev/ttyACM0 115200
connecting to /dev/ttyACM0 with 115200

/home/pi/homeduinojs/node_modules/bluebird/js/main/promise.js:673
            throw e;
                  ^
TimeoutError: operation timed out
    at afterTimeout (/home/pi/homeduinojs/node_modules/bluebird/js/main/timers.js:11:15)
    at timeoutTimeout (/home/pi/homeduinojs/node_modules/bluebird/js/main/timers.js:53:9)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)
pi@raspberrypi:~/homeduinojs$  

I think the issue lies in opening the actual port
any ideas?

**Comment by Icesory** [comment]
Do you have an Arduino with Homeduino installed connected to your USB port? And is the ttyAMC0 port the right port? Normally this is ttyUSB0

**Comment by ivo1981** [comment]
Yes to both, if I run the make monitor it works just fine
A little clarification; 
I run it on a mega, I adapted the Make file for the correct port and board.
With the make monitor everything works as it should, I get ready and ACK's and can send commands

**Comment by michas79** [comment]
It is the same for me. 
 sudo ./client.js /dev/ttyUSB0 115200

brings

connecting to /dev/ttyUSB0 with 115200

/home/pi/git/homeduinojs/node_modules/bluebird/js/main/promise.js:673
            throw e;
                  ^
TimeoutError: operation timed out
    at afterTimeout (/home/pi/git/homeduinojs/node_modules/bluebird/js/main/timers.js:11:15)
    at timeoutTimeout (/home/pi/git/homeduinojs/node_modules/bluebird/js/main/timers.js:53:9)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

I use an Arduino Pro Mini.

**Comment by Icesory** [comment]
This package is designed to work with pimatic-homeduino. In this constellation it works great. Eventually handles Homeduino some call different. You should take a look into the code and  the integration of homeduinojs

**Comment by ivo1981** [comment]
I think the whole issue is that the client doesn't specify a connection timeout upon connecting.
I tried to find out how pimatic connects to homeduino, but I'm new to nodejs, and coffee makes it even harder. 
@Icesory Would I be a lot of work to fix the client so it sets up the connection in the same way as pimatic?

**Comment by ivo1981** [comment]
@michas79 
Did you make any progress?

**Comment by michas79** [comment]
@ivo1981 
Sorry, didn't had much time.

If you need a fix, just change line 96 in homeduinojs\lib\board.js from this:

return this.pendingConnect = this.driver.connect(timeout, retries);

to this:

return this.pendingConnect = this.driver.connect(this.timeout, this.retries);

**Comment by ivo1981** [comment]
@michas79 
Thanks for the reply! Will try this tomorrow.

**Comment by mwittig** [comment]
I think this issue can be closed as the suggested fix had been committed. Please re-open if the problem still occurs.

https://github.com/pimatic/homeduinojs/blob/master/lib/board.js#L96
